@startuml

title __LSN3CLASSES1's Class Diagram__\n

  namespace org.launchcode.java.demos {
    namespace lsn3classes1 {
      class org.launchcode.java.demos.lsn3classes1.Course {
          - department : String
          - instructor : String
          - studentRoster : HashMap<Student, Integer>
          - subject : String
          + Course()
          + equals()
          + getDepartment()
          + getInstructor()
          + getStudentRoster()
          + getSubject()
          + hashCode()
          + setDepartment()
          + setInstructor()
          + setName()
          + setStudentRoster()
          + toString()
      }
    }
  }
  

  namespace org.launchcode.java.demos {
    namespace lsn3classes1 {
      class org.launchcode.java.demos.lsn3classes1.SchoolPractice {
          {static} + main()
      }
    }
  }
  

  namespace org.launchcode.java.demos {
    namespace lsn3classes1 {
      class org.launchcode.java.demos.lsn3classes1.Student {
          - gpa : double
          - name : String
          - numberOfCredits : int
          - studentId : int
          + Student()
          + Student()
          + getGpa()
          + getName()
          + getNumberOfCredits()
          + getStudentId()
          + setGpa()
          + setName()
          + setStudentId()
          - setNumberOfCredits()
      }
    }
  }
  

  namespace org.launchcode.java.demos {
    namespace lsn3classes1 {
      class org.launchcode.java.demos.lsn3classes1.Teacher {
          - firstName : String
          - lastName : String
          - subject : String
          - yearsTeaching : int
          + Teacher()
          + getFirstName()
          + getLastName()
          + getSubject()
          + getYearsTeaching()
          + setFirstName()
          + setLastName()
          + setSubject()
          + setYearsTeaching()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
