@startuml

title __LSN7INTERFACES's Class Diagram__\n

  namespace org.launchcode.java.demos {
    namespace lsn7interfaces {
      class org.launchcode.java.demos.lsn7interfaces.Case {
          - cones : ArrayList<Cone>
          - flavors : ArrayList<Flavor>
          + Case()
          + getCones()
          + getFlavors()
          + setCones()
          + setFlavors()
      }
    }
  }
  

  namespace org.launchcode.java.demos {
    namespace lsn7interfaces {
      class org.launchcode.java.demos.lsn7interfaces.Cone {
          + Cone()
      }
    }
  }
  

  namespace org.launchcode.java.demos {
    namespace lsn7interfaces {
      class org.launchcode.java.demos.lsn7interfaces.Flavor {
          + Flavor()
      }
    }
  }
  

  namespace org.launchcode.java.demos {
    namespace lsn7interfaces {
      abstract class org.launchcode.java.demos.lsn7interfaces.Ingredient {
          - allergens : ArrayList<String>
          - cost : double
          - name : String
          + Ingredient()
          + getAllergens()
          + getCost()
          + getName()
          + setAllergens()
          + setCost()
          + setName()
          + toString()
      }
    }
  }
  

  namespace org.launchcode.java.demos {
    namespace lsn7interfaces {
      class org.launchcode.java.demos.lsn7interfaces.Main {
          {static} + main()
      }
    }
  }
  

  org.launchcode.java.demos.lsn7interfaces.Cone -up-|> org.launchcode.java.demos.lsn7interfaces.Ingredient
  org.launchcode.java.demos.lsn7interfaces.Flavor -up-|> org.launchcode.java.demos.lsn7interfaces.Ingredient


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
