@startuml

title __LSN4CLASSES2's Class Diagram__\n

  namespace org.launchcode.java.demos {
    namespace lsn4classes2 {
      class org.launchcode.java.demos.lsn4classes2.Course {
          - enrolledStudents : ArrayList<Student>
          - topic : String
          + equals()
          + getEnrolledStudents()
          + getInstructor()
          + getTopic()
          + hashCode()
          + setEnrolledStudents()
          + setInstructor()
          + setTopic()
          + toString()
      }
    }
  }
  

  namespace org.launchcode.java.demos {
    namespace lsn4classes2 {
      class org.launchcode.java.demos.lsn4classes2.Student {
          - gpa : double
          - name : String
          {static} - nextStudentId : int
          - numberOfCredits : int
          - studentId : int
          + Student()
          + Student()
          + Student()
          + addGrade()
          + equals()
          + getGpa()
          + getGradeLevel()
          + getName()
          + getNumberOfCredits()
          + getStudentId()
          + hashCode()
          {static} + main()
          + setGpa()
          + setName()
          + setStudentId()
          + studentInfo()
          + toString()
          - setNumberOfCredits()
      }
    }
  }
  

  namespace org.launchcode.java.demos {
    namespace lsn4classes2 {
      class org.launchcode.java.demos.lsn4classes2.Teacher {
          - firstName : String
          - lastName : String
          - subject : String
          - yearsTeaching : int
          + Teacher()
          + getFirstName()
          + getLastName()
          + getSubject()
          + getYearsTeaching()
          + setFirstName()
          + setLastName()
          + setSubject()
          + setYearsTeaching()
      }
    }
  }
  

  org.launchcode.java.demos.lsn4classes2.Course o-- org.launchcode.java.demos.lsn4classes2.Teacher : instructor


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
